apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    platform.example/team: {{ .Values.team | quote }}
    platform.example/environment: {{ .Values.environmentType | quote }}
    platform.example/managed: "true"
