name: sample-api
namespace: team-demo-sample-api
team: team-demo
environmentType: development
ttlHours: 12
profile: small
image: nginxinc/nginx-unprivileged:1.27-alpine
postgresql: false
redis: false
observability: true
ingress:
  enabled: true
  className: nginx
  host: sample-api.localhost
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 70
resources:
  requests: {cpu: 250m, memory: 256Mi}
  limits: {cpu: 500m, memory: 512Mi}
