apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: {name: platform-environments, namespace: argocd}
spec:
  project: default
  source:
    repoURL: https://github.com/bepoadewale/ai-platform-control-plane.git
    targetRevision: codex/week-01-platform-control-plane
    path: platform/helm/golden-path
  destination: {server: https://kubernetes.default.svc, namespace: default}
  syncPolicy: {automated: {prune: false, selfHeal: false}}
