apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-platform-control-plane-runtime
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: ai-platform-control-plane
spec:
  project: default
  source:
    repoURL: https://github.com/Bepoadewale/ai-platform-control-plane.git
    targetRevision: main
    path: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
